### PR TITLE
Changes for MP8 V2 in 2024

### PR DESCRIPTION
**Pull request by gputcha2**

### CODE REVIEW

**Comment by rfarivar** [comment]
Is the PR ready for review?

**Comment by gputcha2** [comment]
Hello Professor,

Yes this PR is ready to review. We can discuss further on a call if you'd like!

**Comment by gputcha2** [comment]
One thing I wanted to ask about was whether or not to keep the SQL Context lines in the java templates. They are still used in the solutions so they could be beneficial to students while solving the assignment.

**Review by gputcha2 — COMMENTED** [review]
Review complete - Ready to merge.

**Pull request merged**
